name: Build AppImage

on:
  push:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build AppImage
        run: npx electron-builder --linux AppImage

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NebulitonAppImage
          path: dist/*.AppImage
